services:
  api:
    environment:
      PORT: ${API_PORT:-3000}
    ports:
      - ${API_PORT:-3000}:${API_PORT:-3000}

  test: {}

  web:
    depends_on:
      api:
        condition: service_started
    ports:
      - ${WEB_PORT:-5173}:${WEB_PORT:-5173}
