export const timezones = [
  ["台灣", "台北市", "台北", "Asia/Taipei"],
  ["台灣", "新北市", "板橋", "Asia/Taipei"],
  ["台灣", "桃園市", "桃園", "Asia/Taipei"],
  ["台灣", "台中市", "台中", "Asia/Taipei"],
  ["台灣", "台南市", "台南", "Asia/Taipei"],
  ["台灣", "高雄市", "高雄", "Asia/Taipei"],
  ["台灣", "基隆市", "基隆", "Asia/Taipei"],
  ["台灣", "新竹市", "新竹", "Asia/Taipei"],
  ["台灣", "嘉義市", "嘉義", "Asia/Taipei"],
  ["台灣", "新竹縣", "竹北", "Asia/Taipei"],
  ["台灣", "苗栗縣", "苗栗", "Asia/Taipei"],
  ["台灣", "彰化縣", "彰化", "Asia/Taipei"],
  ["台灣", "南投縣", "南投", "Asia/Taipei"],
  ["台灣", "雲林縣", "斗六", "Asia/Taipei"],
  ["台灣", "嘉義縣", "太保", "Asia/Taipei"],
  ["台灣", "屏東縣", "屏東", "Asia/Taipei"],
  ["台灣", "宜蘭縣", "宜蘭", "Asia/Taipei"],
  ["台灣", "花蓮縣", "花蓮", "Asia/Taipei"],
  ["台灣", "台東縣", "台東", "Asia/Taipei"],
  ["台灣", "澎湖縣", "馬公", "Asia/Taipei"],
  ["台灣", "金門縣", "金城", "Asia/Taipei"],
  ["台灣", "連江縣", "南竿", "Asia/Taipei"],
  ["美國", "阿拉巴馬州", "伯明翰", "America/Chicago"],
  ["美國", "阿拉斯加州（大部分地區）", "安克拉治、朱諾", "America/Anchorage"],
  ["美國", "阿拉斯加州（阿留申群島西部）", "阿達克", "America/Adak"],
  ["美國", "亞利桑那州（大部分地區）", "鳳凰城、圖森", "America/Phoenix"],
  ["美國", "亞利桑那州（納瓦霍族保留地）", "金曼", "America/Denver"],
  ["美國", "阿肯色州", "小石城", "America/Chicago"],
  ["美國", "加利福尼亞州", "洛杉磯、舊金山", "America/Los_Angeles"],
  ["美國", "科羅拉多州", "丹佛", "America/Denver"],
  ["美國", "康涅狄格州", "哈特福德、紐黑文", "America/New_York"],
  ["美國", "特拉華州", "威明頓、多佛", "America/New_York"],
  ["美國", "哥倫比亞特區", "華盛頓特區", "America/New_York"],
  ["美國", "佛羅里達州（西部）", "彭薩科拉、巴拿馬城", "America/Chicago"],
  ["美國", "佛羅里達州（東部）", "邁阿密、奧蘭多", "America/New_York"],
  ["美國", "喬治亞州", "亞特蘭大、薩凡納", "America/New_York"],
  ["美國", "夏威夷州", "檀香山、希洛", "Pacific/Honolulu"],
  ["美國", "愛達荷州（北部）", "科達倫、莫斯科", "America/Los_Angeles"],
  ["美國", "愛達荷州（南部）", "博伊西、愛達荷福爾斯", "America/Denver"],
  ["美國", "伊利諾伊州", "芝加哥、斯普林菲爾德", "America/Chicago"],
  [
    "美國",
    "印第安納州（西北和西南地區）",
    "加里、埃文斯維爾",
    "America/Chicago",
  ],
  [
    "美國",
    "印第安納州（其他地區）",
    "印第安納波利斯、南本德",
    "America/Indiana/Indianapolis",
  ],
  ["美國", "愛荷華州", "得梅因、錫達拉皮茲", "America/Chicago"],
  ["美國", "堪薩斯州", "威奇托、托皮卡", "America/Chicago"],
  ["美國", "肯塔基州（西部）", "帕迪尤卡、歐文斯伯勒", "America/Chicago"],
  ["美國", "肯塔基州（東部）", "路易維爾、列剋星敦", "America/New_York"],
  ["美國", "路易斯安那州", "新奧爾良、巴吞魯日", "America/Chicago"],
  ["美國", "緬因州", "波特蘭、班戈", "America/New_York"],
  ["美國", "馬里蘭州", "巴爾的摩、安納波利斯", "America/New_York"],
  ["美國", "麻薩諸塞州", "波士頓、伍斯特", "America/New_York"],
  ["美國", "密西根州（大部分地區）", "底特律、大急流城", "America/Detroit"],
  ["美國", "密西根州（上半島西部）", "馬凱特、霍頓", "America/Menominee"],
  ["美國", "明尼蘇達州", "明尼阿波利斯、聖保羅", "America/Chicago"],
  ["美國", "密西西比州", "傑克遜、比洛克西", "America/Chicago"],
  ["美國", "密蘇里州", "堪薩斯城、聖路易斯", "America/Chicago"],
  ["美國", "蒙大拿州", "比靈斯、米蘇拉", "America/Denver"],
  ["美國", "內布拉斯加州（大部分地區）", "奧馬哈、林肯", "America/Chicago"],
  ["美國", "內布拉斯加州（西部）", "斯科茨布拉夫、查德隆", "America/Denver"],
  ["美國", "內華達州", "拉斯維加斯、里諾", "America/Los_Angeles"],
  ["美國", "新罕布什爾州", "曼徹斯特、納舒厄", "America/New_York"],
  ["美國", "新澤西州", "紐瓦克、澤西市", "America/New_York"],
  ["美國", "新墨西哥州", "阿爾伯克基、聖塔菲", "America/Denver"],
  ["美國", "紐約州", "紐約市、水牛城", "America/New_York"],
  ["美國", "北卡羅來納州", "夏洛特、羅利", "America/New_York"],
  ["美國", "北達科他州（大部分地區）", "法戈、俾斯麥", "America/Chicago"],
  ["美國", "北達科他州（西南部）", "迪金森、威利斯頓", "America/Denver"],
  ["美國", "俄亥俄州", "克里夫蘭、哥倫布", "America/New_York"],
  ["美國", "奧克拉荷馬州", "奧克拉荷馬城、塔爾薩", "America/Chicago"],
  ["美國", "奧勒岡州（大部分地區）", "波特蘭、尤金", "America/Los_Angeles"],
  ["美國", "奧勒岡州（馬盧爾縣）", "安大略市", "America/Boise"],
  ["美國", "賓夕法尼亞州", "費城、匹茲堡", "America/New_York"],
  ["美國", "羅德島州", "普羅維登斯、克蘭斯頓", "America/New_York"],
  ["美國", "南卡羅來納州", "查爾斯頓、哥倫比亞", "America/New_York"],
  ["美國", "南達科他州（東部）", "蘇瀑、阿伯丁", "America/Chicago"],
  ["美國", "南達科他州（西部）", "拉皮德城、斯皮爾菲", "America/Denver"],
  ["美國", "田納西州（東部）", "諾克斯維爾", "America/New_York"],
  ["美國", "田納西州（大部分地區）", "納什維爾 ", "America/Chicago"],
  ["美國", "德克薩斯州（大部分地區）", "達拉斯 ", "America/Chicago"],
  ["美國", "德克薩斯州（西部）", "埃爾帕索", "America/Denver"],
  ["美國", "猶他州", "鹽湖城", "America/Denver"],
  ["美國", "佛蒙特州", "伯靈頓", "America/New_York"],
  ["美國", "維吉尼亞州", "弗吉尼亞海灘", "America/New_York"],
  ["美國", "西維吉尼亞州", "查爾斯頓", "America/New_York"],
  ["美國", "威斯康辛州", "密爾沃基", "America/Chicago"],
  ["美國", "懷俄明州", "夏延", "America/Denver"],
  ["美國", "哥倫比亞特區", "華盛頓特區", "America/New_York"],
  ["美國", "波多黎各", "聖胡安", "America/Puerto_Rico"],
  ["美國", "美屬維京群島", "夏洛特阿馬利亞", "America/St_Thomas"],
  ["美國", "關島", "哈加特納", "Pacific/Guam"],
  ["美國", "美屬薩摩亞", "帕果帕果、中途島", "Pacific/Pago_Pago"],
  ["美國", "北馬里亞納群島", "塞班", "Pacific/Saipan"],
  ["澳洲", "科科斯（基林）群島", "西島", "Indian/Cocos"],
  ["澳洲", "聖誕島", "飛魚灣", "Indian/Christmas"],
  ["澳洲", "西澳", "柏斯", "Australia/Perth"],
  ["澳洲", "北領地", "達爾文", "Australia/Darwin"],
  ["澳洲", "南澳", "阿得雷德", "Australia/Adelaide"],
  ["澳洲", "昆士蘭", "布里斯本", "Australia/Brisbane"],
  ["澳洲", "新南威爾斯", "雪梨", "Australia/Sydney"],
  ["澳洲", "維多利亞", "墨爾本", "Australia/Melbourne"],
  ["澳洲", "塔斯馬尼亞", "霍巴特", "Australia/Hobart"],
  ["澳洲", "首都領地", "坎培拉", "Australia/Sydney"],
  ["澳洲", "諾福克島", "金斯頓", "Pacific/Norfolk"],
  ["澳洲", "豪勳爵島", "豪勳爵島", "Australia/LHI"],
  ["阿富汗", "東阿富汗（聯合國分區）", "賈拉拉巴德", "Asia/Kabul"],
  ["阿富汗", "中阿富汗（聯合國分區）", "喀布爾", "Asia/Kabul"],
  ["阿富汗", "西阿富汗（聯合國分區）", "赫拉特", "Asia/Kabul"],
  ["阿富汗", "東北阿富汗（聯合國分區）", "昆都士", "Asia/Kabul"],
  ["阿富汗", "東南阿富汗（聯合國分區）", "加茲尼", "Asia/Kabul"],
  ["阿富汗", "西北阿富汗（聯合國分區）", "馬扎里沙里夫", "Asia/Kabul"],
  ["阿富汗", "西南阿富汗（聯合國分區）", "拉什卡爾加", "Asia/Kabul"],
  ["阿爾巴尼亞", "培拉特州 (Qarku i Beratit)", "培拉特", "Europe/Tirane"],
  ["阿爾巴尼亞", "第巴爾州 (Qarku i Dibrë)", "佩什科比", "Europe/Tirane"],
  ["阿爾巴尼亞", "杜勒斯州 (Qarku i Durrësit)", "杜勒斯", "Europe/Tirane"],
  ["阿爾巴尼亞", "愛爾巴桑州 (Qarku i Elbasanit)", "愛爾巴桑", "Europe/Tirane"],
  ["阿爾巴尼亞", "費里州 (Qarku i Fierit)", "費里", "Europe/Tirane"],
  [
    "阿爾巴尼亞",
    "吉諾卡斯特州 (Qarku i Gjirokastrë)",
    "吉諾卡斯特",
    "Europe/Tirane",
  ],
  ["阿爾巴尼亞", "科赤州 (Qarku i Korçë)", "科赤", "Europe/Tirane"],
  ["阿爾巴尼亞", "庫克斯州 (Qarku i Kukësit)", "庫克斯", "Europe/Tirane"],
  ["阿爾巴尼亞", "萊什州 (Qarku i Lezhë)", "萊什", "Europe/Tirane"],
  ["阿爾巴尼亞", "士科德州 (Qarku i Shkodrë)", "士科德", "Europe/Tirane"],
  ["阿爾巴尼亞", "地拉那州 (Qarku i Tiranë)", "地拉那", "Europe/Tirane"],
  ["阿爾巴尼亞", "夫羅勒州 (Qarku i Vlorë)", "夫羅勒", "Europe/Tirane"],
  ["阿爾及利亞", "阿爾及利亞", "阿爾及爾", "Africa/Algiers"],
  ["安道爾公國", "安道爾", "老安道爾", "Europe/Andorra"],
  ["安哥拉共和國", "安哥拉", "盧安達", "Africa/Luanda"],
  ["安地卡及巴布達", "安地卡島", "聖約翰", "America/Antigua"],
  [
    "阿根廷",
    "布宜諾斯艾利斯",
    "布宜諾斯艾利斯",
    "America/Argentina/Buenos_Aires",
  ],
  ["阿根廷", "卡塔馬卡省", "卡塔馬卡", "America/Argentina/Catamarca"],
  ["阿根廷", "丘布特省", "羅森", "America/Argentina/ComodRivadavia"],
  ["阿根廷", "科爾多瓦省", "科爾多瓦", "America/Argentina/Cordoba"],
  ["阿根廷", "胡胡伊省", "聖薩爾瓦多-胡胡伊", "America/Argentina/Jujuy"],
  ["阿根廷", "拉里奧哈省", "拉里奧哈", "America/Argentina/La_Rioja"],
  ["阿根廷", "門多薩省", "門多薩", "America/Argentina/Mendoza"],
  ["阿根廷", "聖克魯斯省", "里奧加耶戈斯", "America/Argentina/Rio_Gallegos"],
  ["阿根廷", "薩爾塔省", "薩爾塔", "America/Argentina/Salta"],
  ["阿根廷", "聖胡安省", "聖胡安", "America/Argentina/San_Juan"],
  ["阿根廷", "聖路易斯省", "聖路易斯", "America/Argentina/San_Luis"],
  ["阿根廷", "圖庫曼省", "聖米格爾-圖庫曼", "America/Argentina/Tucuman"],
  ["阿根廷", "火地群島省", "烏斯懷亞市", "America/Argentina/Ushuaia"],
  ["亞美尼亞", "亞美尼亞", "葉里溫", "Asia/Yerevan"],
  ["奧地利", "奧地利共和國", "維也納", "Europe/Vienna"],
  ["亞塞拜然", "亞塞拜然共和國", "巴庫", "Asia/Baku"],
  ["英國", "英格蘭", "倫敦", "Europe/London"],
  ["英國", "蘇格蘭", "愛丁堡", "Europe/London"],
  ["英國", "威爾士", "卡迪夫 ", "Europe/London"],
  ["英國", "北愛爾蘭", "貝爾法斯特", "Europe/Belfast"],
  ["英國", "根西行政區", "聖彼得港", "Europe/London"],
  ["英國", "曼島", "道格拉斯", "Europe/London"],
  ["英國", "澤西行政區", "聖赫利爾", "Europe/London"],
  ["英國", "聖赫勒拿及其屬地", "詹姆士敦", "Europe/London"],
  ["英國", "直布羅陀", "直布羅陀", "Europe/Gibraltar"],
  ["英國", "英屬基地區", "埃皮斯科皮兵營", "Europe/London"],
  ["英國", "英屬印度洋領地", "迪亞哥加西亞", "Indian/Chagos"],
  ["英國", "南喬治亞與南桑威奇群島", "愛德華國王角", "Atlantic/South_Georgia"],
  ["英國", "福克蘭群島", "史坦利", "Atlantic/Stanley"],
  ["英國", "安圭拉", "瓦利", "America/Anguilla"],
  ["英國", "英屬維爾京群島", "羅德城", "America/Tortola"],
  ["英國", "蒙哲臘", "普利茅斯", "America/Montserrat"],
  ["英國", "土克凱可群島", "科伯恩城", "America/Grand_Turk"],
  ["英國", "百慕達", "漢米爾頓", "Atlantic/Bermuda"],
  ["英國", "開曼群島", "喬治城", "America/Cayman"],
  ["英國", "皮特凱恩群島", "亞當斯敦 ", "Pacific/Pitcairn"],
  ["巴哈馬", "巴哈馬國", "拿騷", "America/Nassau"],
  ["巴林", "巴林王國", "麥納瑪", "Asia/Bahrain"],
  ["孟加拉", "孟加拉人民共和國", "達卡", "Asia/Dhaka"],
  ["巴貝多", "巴貝多", "橋鎮", "America/Barbados"],
  ["白俄羅斯", "白俄羅斯共和國", "明斯克", "Europe/Minsk"],
  ["比利時", "比利時王國", "布魯塞爾", "Europe/Brussels"],
  ["貝里斯", "貝里斯", "貝爾墨潘", "America/Belize"],
  ["貝南", "貝南共和國", "新港（波多諾）", "Africa/Porto-Novo"],
  ["不丹", "不丹王國", "辛布", "Asia/Thimbu"],
  ["波利維亞", "玻利維亞多民族國", "拉巴斯", "America/La_Paz"],
  ["波赫", "波士尼亞與赫塞哥維納", "塞拉耶佛", "Europe/Sarajevo"],
  ["波扎那", "波札那共和國", "嘉伯隆里", "Africa/Gaborone"],
  ["汶萊", "汶萊和平之國", "斯里巴卡旺", "Asia/Brunei"],
  ["保加利亞", "保加利亞共和國", "索非亞", "Europe/Sofia"],
  ["布吉納法索", "布吉納法索", "瓦加杜古", "Africa/Ouagadougou"],
  ["蒲隆地", "蒲隆地共和國", "布松布拉", "Africa/Bujumbura"],
  ["巴布亞紐幾內亞", "布干維爾自治區", "布卡（Buka）", "Pacific/Bougainville"],
  ["巴布亞紐幾內亞", "西部省", "達魯（Daru）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "海灣省", "凱里馬（Kerema）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "中央省", "貝雷納（Bereina）", "Pacific/Port_Moresby"],
  [
    "巴布亞紐幾內亞",
    "國家首都區",
    "摩斯比港（Port Moresby）",
    "Pacific/Port_Moresby",
  ],
  ["巴布亞紐幾內亞", "米爾恩灣省", "阿洛陶（Alotau）", "Pacific/Port_Moresby"],
  [
    "巴布亞紐幾內亞",
    "北部省",
    "波波迪塔（Popondetta）",
    "Pacific/Port_Moresby",
  ],
  ["巴布亞紐幾內亞", "南高地省", "曼迪（Mendi）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "東高地省", "戈羅卡（Goroka）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "欽布省", "昆迪亞瓦（Kundiawa）", "Pacific/Port_Moresby"],
  [
    "巴布亞紐幾內亞",
    "西高地省",
    "芒特哈根（Mount Hagen",
    "Pacific/Port_Moresby",
  ],
  ["巴布亞紐幾內亞", "吉瓦卡省", "孔帕（Kundiawa）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "恩加省", "瓦比亞（Wabag）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "赫拉省", "塔里（Tari）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "莫羅貝省", "萊城（Lae）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "馬當省", "馬當（Madang）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "東塞皮克省", "韋瓦克（Wewak）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "桑道恩省", "瓦尼莫（Vanimo）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "馬努斯省", "洛倫高（Lorengau）", "Pacific/Port_Moresby"],
  ["巴布亞紐幾內亞", "新愛爾蘭省", "卡維恩（Kavieng）", "Pacific/Port_Moresby"],
  [
    "巴布亞紐幾內亞",
    "東新不列顛省",
    "拉包爾（Rabaul）",
    "Pacific/Port_Moresby",
  ],
  ["巴布亞紐幾內亞", "西新不列顛省", "金貝（Kimbe）", "Pacific/Port_Moresby"],
  ["巴西", "阿克里州 (Acre)", "里奧布朗庫 (Rio Branco)", "America/Rio_Branco"],
  [
    "巴西",
    "朗多尼亞州 (Rondônia)",
    "波多韋柳 (Porto Velho)",
    "America/Porto_Velho",
  ],
  ["巴西", "亞馬遜州 (Amazonas)", "瑪瑙斯 (Manaus)", "America/Manaus"],
  ["巴西", "羅賴馬州 (Roraima)", "博阿維斯塔 (Boa Vista)", "America/Boa_Vista"],
  ["巴西", "馬托格羅索州 (Mato Grosso)", "庫亞巴 (Cuiabá)", "America/Cuiaba"],
  [
    "巴西",
    "南馬托格羅索州 (Mato Grosso do Sul)",
    "大坎普 (Campo Grande)",
    "America/Campo_Grande",
  ],
  ["巴西", "帕拉州 (Pará)", "貝倫 (Belém)", "America/Belem"],
  ["巴西", "阿馬帕州 (Amapá)", "馬卡帕 (Macapá)", "America/Belem"],
  ["巴西", "托坎廷斯州 (Tocantins)", "帕爾馬斯（Palmas）", "America/Araguaina"],
  ["巴西", "馬拉尼昂州 (Maranhão)", "聖路易斯 (São Luís)", "America/Fortaleza"],
  ["巴西", "皮奧伊州 (Piauí)", "特雷西納 (Teresina)", "America/Fortaleza"],
  ["巴西", "塞阿拉州 (Ceará)", "福塔萊薩 (Fortaleza)", "America/Fortaleza"],
  [
    "巴西",
    "北里奧格蘭德州 (Rio Grande do Norte)",
    "納塔爾 (Natal)",
    "America/Fortaleza",
  ],
  [
    "巴西",
    "帕拉伊巴州 (Paraíba)",
    "若昂佩索阿 (João Pessoa)",
    "America/Fortaleza",
  ],
  ["巴西", "伯南布哥州 (Pernambuco)", "累西腓 (Recife)", "America/Recife"],
  ["巴西", "阿拉戈斯州 (Alagoas)", "馬塞約 (Maceió)", "America/Maceio"],
  ["巴西", "塞爾希培州 (Sergipe)", "阿拉卡茹 (Aracaju)", "America/Maceio"],
  ["巴西", "巴伊亞州 (Bahia)", "薩爾瓦多 (Salvador)", "America/Bahia"],
  [
    "巴西",
    "米納斯吉拉斯州 (Minas Gerais)",
    "貝洛奧里藏特 (Belo Horizonte)",
    "America/Sao_Paulo",
  ],
  ["巴西", "聖保羅州 (São Paulo)", "聖保羅州 (São Paulo)", "America/Sao_Paulo"],
  [
    "巴西",
    "里約熱內盧州 (Rio de Janeiro)",
    "里約熱內盧州 (Rio de Janeiro)",
    "America/Sao_Paulo",
  ],
  [
    "巴西",
    "聖埃斯皮里圖州 (Espírito Santo)",
    "維多利亞 (Vitória)",
    "America/Sao_Paulo",
  ],
  ["巴西", "巴拉那州 (Paraná)", "庫里提巴 (Curitiba)", "America/Sao_Paulo"],
  [
    "巴西",
    "聖卡塔琳娜州 (Santa Catarina)",
    "弗洛里亞諾波利斯 (Florianópolis)",
    "America/Sao_Paulo",
  ],
  [
    "巴西",
    "南里約格蘭德州 (Rio Grande do Sul)",
    "阿雷格里港 (Porto Alegre)",
    "America/Sao_Paulo",
  ],
  ["巴西", "戈亞斯州 (Goiás)", "戈亞尼亞 (Goiânia)", "America/Sao_Paulo"],
  [
    "巴西",
    "巴西利亞聯邦區 (Distrito Federa)",
    "巴西利亞 (Brasília)",
    "America/Sao_Paulo",
  ],
  [
    "巴西",
    "費爾南多-迪諾羅尼亞群島",
    "費爾南多-迪諾羅尼亞群島",
    "America/Noronha",
  ],
  ["加拿大", "紐芬蘭", "聖約翰斯", "America/St_Johns"],
  ["加拿大", "拉布拉多省（東南部）", "藍斯奧盧", "America/St_Johns"],
  ["加拿大", "拉布拉多省（大部分地區）", "納因", "America/Goose_Bay"],
  ["加拿大", "新布倫瑞克省", "蒙克頓", "America/Moncton"],
  ["加拿大", "新斯科舍省", "哈利法克斯", "America/Halifax"],
  ["加拿大", "愛德華王子島省", "夏洛特敦", "America/Halifax"],
  ["加拿大", "馬格達倫群島", "聖勞倫斯灣", "America/Halifax"],
  [
    "加拿大",
    "魁北克省（納塔什泉河以東）",
    "布朗薩布隆",
    "America/Blanc-Sablon",
  ],
  ["加拿大", "魁北克省", "蒙特婁", "America/Montreal"],
  ["加拿大", "南安普頓島", "珊瑚港", "America/Coral_Harbour"],
  ["加拿大", "安大略省（90°以東）", "多倫多", "America/Toronto"],
  [
    "加拿大",
    "安大略省 （西北部）",
    "安大略省 （西北部）",
    "America/Rainy_River",
  ],
  ["加拿大", "努納武特地區（85°以東）", "伊奎特", "America/Iqaluit"],
  ["加拿大", "努納武特地區（中部）", "雷索盧特", "America/Resolute"],
  ["加拿大", "努納武特地區（奇里瓦基）", "蘭京海口", "America/Rankin_Inlet"],
  ["加拿大", "努納武特地區（120°以西）", "劍橋灣", "America/Cambridge_Bay"],
  ["加拿大", "馬尼托巴省", "溫尼伯", "America/Winnipeg"],
  ["加拿大", "薩克其萬省", "薩斯卡通", "America/Regina"],
  ["加拿大", "亞伯達省", "卡爾加利", "America/Edmonton"],
  ["加拿大", "勞埃德明斯特", "勞埃德明斯特", "America/Creston"],
  ["加拿大", "英屬哥倫比亞省（山地）", "道森溪", "America/Dawson_Creek"],
  ["加拿大", "英屬哥倫比亞省（大部分）", "溫哥華", "America/Vancouver"],
  ["加拿大", "育空地區", "白馬市", "America/Whitehorse"],
  ["加拿大", "西北地區", "黃刀鎮", "America/Yellowknife"],
  ["剛果民主共和國", "金沙薩省", "金沙薩 (Kinshasa)", "Africa/Kinshasa"],
  ["剛果民主共和國", "中剛果省", "馬塔迪 (Matadi)", "Africa/Kinshasa"],
  ["剛果民主共和國", "奎盧省", "基奎特 (Kikwit)", "Africa/Kinshasa"],
  ["剛果民主共和國", "寬果省", "班頓杜 (Bandundu)", "Africa/Kinshasa"],
  ["剛果民主共和國", "馬伊恩東貝省", "伊農戈 (Inongo)", "Africa/Kinshasa"],
  ["剛果民主共和國", "赤道省", "姆班達卡 (Mbandaka)", "Africa/Kinshasa"],
  ["剛果民主共和國", "楚阿帕省", "博恩代 (Boende)", "Africa/Kinshasa"],
  ["剛果民主共和國", "蒙加拉省", "利薩拉 (Lisala)", "Africa/Kinshasa"],
  ["剛果民主共和國", "北烏班吉省", "戈巴多萊 (Gbadolite)", "Africa/Kinshasa"],
  ["剛果民主共和國", "南烏班吉省", "蓋梅納 (Gemena)", "Africa/Kinshasa"],
  ["剛果民主共和國", "下韋萊省", "布塔 (Buta)", "Africa/Kinshasa"],
  ["剛果民主共和國", "開賽省", "盧埃博 (Luebo)", "Africa/Kinshasa"],
  ["剛果民主共和國", "桑庫魯省", "洛賈 (Lodja)", "Africa/Kinshasa"],
  ["剛果民主共和國", "上韋萊省", "伊西羅 (Isiro)", "Africa/Lubumbashi"],
  ["剛果民主共和國", "伊圖里省", "布尼亞 (Bunia)", "Africa/Lubumbashi"],
  ["剛果民主共和國", "喬波省", "基桑加尼 (Kisangani)", "Africa/Lubumbashi"],
  ["剛果民主共和國", "北基伍省", "戈馬 (Goma)", "Africa/Lubumbashi"],
  ["剛果民主共和國", "南基伍省", "布卡武 (Bukavu)", "Africa/Lubumbashi"],
  ["剛果民主共和國", "馬涅馬省", "金杜 (Kindu)", "Africa/Lubumbashi"],
  ["剛果民主共和國", "盧阿拉巴省", "科盧韋齊 (Kolwezi)", "Africa/Lubumbashi"],
  [
    "剛果民主共和國",
    "上加丹加省",
    "盧本巴希 (Lubumbashi)",
    "Africa/Lubumbashi",
  ],
  ["剛果民主共和國", "上洛馬米省", "卡米納 (Kamina)", "Africa/Lubumbashi"],
  ["剛果民主共和國", "坦噶尼喀省", "卡萊米 (Kalemie)", "Africa/Lubumbashi"],
  ["剛果民主共和國", "洛馬米省", "卡賓達 (Kabinda)", "Africa/Lubumbashi"],
  [
    "剛果民主共和國",
    "東開賽省",
    "姆布吉馬伊 (Mbuji-Mayi)",
    "Africa/Lubumbashi",
  ],
  ["剛果民主共和國", "盧盧阿省", "卡南加 (Kananga)", "Africa/Lubumbashi"],
  [
    "智利",
    "復活節島 (Isla de Pascua)",
    "漢加羅阿 (Hanga Roa)",
    "Pacific/Easter",
  ],
  [
    "智利",
    "馬加蘭大區 (Magallanes)",
    "蓬塔阿雷納斯 (Punta Arenas)",
    "America/Punta_Arenas",
  ],
  ["智利", "阿里卡與帕里納科塔大區", "阿里卡 (Arica)", "America/Santiago"],
  ["智利", "塔拉帕卡大區 (Tarapacá)", "伊基克 (Iquique)", "America/Santiago"],
  [
    "智利",
    "安托法加斯塔大區 (Antofagasta)",
    "安托法加斯塔 (Antofagasta)",
    "America/Santiago",
  ],
  ["智利", "阿塔卡馬大區 (Atacama)", "科皮亞波 (Copiapó)", "America/Santiago"],
  ["智利", "科金博大區 (Coquimbo)", "拉塞雷納 (La Serena)", "America/Santiago"],
  [
    "智利",
    "瓦爾帕萊索大區 (Valparaíso)",
    "瓦爾帕萊索 (Valparaíso)",
    "America/Santiago",
  ],
  [
    "智利",
    "聖地亞哥首都大區 (Metropolitana)",
    "聖地亞哥 (Santiago)",
    "America/Santiago",
  ],
  ["智利", "奧伊金斯大區 (O'Higgins)", "蘭卡瓜 (Rancagua)", "America/Santiago"],
  ["智利", "馬烏萊大區 (Maule)", "塔爾卡 (Talca)", "America/Santiago"],
  [
    "智利",
    "比奧比奧大區 (Biobío)",
    "康塞普西翁 (Concepción)",
    "America/Santiago",
  ],
  [
    "智利",
    "阿勞卡尼亞大區 (La Araucanía)",
    "特木科 (Temuco)",
    "America/Santiago",
  ],
  ["智利", "河大區 (Los Ríos)", "瓦爾迪維亞 (Valdivia)", "America/Santiago"],
  ["智利", "湖大區 (Los Lagos)", "蒙特港 (Puerto Montt)", "America/Santiago"],
  ["智利", "艾森大區 (Aysén)", "科伊艾克 (Coyhaique)", "America/Santiago"],
  ["柬埔寨", "柬埔寨王國", "金邊", "Asia/Phnom_Penh"],
  ["喀麥隆", "喀麥隆共和國", "雅溫德", "Africa/Douala"],
  ["維德角", "維德角共和國", "培亞", "Atlantic/Cape_Verde"],
  ["中非", "中非共和國", "班基", "Africa/Bangui"],
  ["查德", "查德共和國", "恩將納", "Africa/Ndjamena"],
  ["中國", "北京市", "北京", "Asia/Shanghai"],
  ["中國", "天津市", "天津", "Asia/Shanghai"],
  ["中國", "上海市", "上海", "Asia/Shanghai"],
  ["中國", "重慶市", "重慶", "Asia/Shanghai"],
  ["中國", "河北省", "石家莊", "Asia/Shanghai"],
  ["中國", "山西省", "太原", "Asia/Shanghai"],
  ["中國", "遼寧省", "瀋陽", "Asia/Shanghai"],
  ["中國", "吉林省", "長春", "Asia/Shanghai"],
  ["中國", "黑龍江省", "哈爾濱", "Asia/Shanghai"],
  ["中國", "江蘇省", "南京", "Asia/Shanghai"],
  ["中國", "浙江省", "杭州", "Asia/Shanghai"],
  ["中國", "安徽省", "合肥", "Asia/Shanghai"],
  ["中國", "福建省", "福州", "Asia/Shanghai"],
  ["中國", "江西省", "南昌", "Asia/Shanghai"],
  ["中國", "山東省", "濟南", "Asia/Shanghai"],
  ["中國", "河南省", "鄭州", "Asia/Shanghai"],
  ["中國", "湖北省", "武漢", "Asia/Shanghai"],
  ["中國", "湖南省", "長沙", "Asia/Shanghai"],
  ["中國", "廣東省", "廣州", "Asia/Shanghai"],
  ["中國", "海南省", "海口", "Asia/Shanghai"],
  ["中國", "四川省", "成都", "Asia/Shanghai"],
  ["中國", "貴州省", "貴陽", "Asia/Shanghai"],
  ["中國", "雲南省", "昆明", "Asia/Shanghai"],
  ["中國", "陝西省", "西安", "Asia/Shanghai"],
  ["中國", "甘肅省", "蘭州", "Asia/Shanghai"],
  ["中國", "青海省", "西寧", "Asia/Shanghai"],
  ["中國", "內蒙古自治區", "呼和浩特", "Asia/Shanghai"],
  ["中國", "廣西壯族自治區", "南寧", "Asia/Shanghai"],
  ["中國", "西藏自治區", "拉薩", "Asia/Shanghai"],
  ["中國", "寧夏回族自治區", "銀川", "Asia/Shanghai"],
  ["中國", "新疆維吾爾自治區", "烏魯木齊", "Asia/Urumqi"],
  ["香港", "香港島", "九龍", "Asia/Hong_Kong"],
  ["澳門", "澳門半島", "氹仔", "Asia/Macau"],
  ["哥倫比亞", "哥倫比亞共和國", "波哥大", "America/Bogota"],
  ["葛摩", "葛摩聯盟", "莫洛尼", "Indian/Comoro"],
  ["剛果共和國", "剛果共和國", "布拉薩", "Africa/Brazzaville"],
  ["哥斯大黎加", "哥斯大黎加共和國", "聖荷西", "America/Costa_Rica"],
  ["克羅埃西亞", "克羅埃西亞共和國", "札格瑞布", "Europe/Zagreb"],
  ["古巴", "古巴共和國", "哈瓦那", "America/Havana"],
  ["塞普勒斯", "塞普勒斯共和國", "尼古西亞", "Asia/Nicosia"],
  ["捷克", "捷克共和國", "布拉格", "Europe/Prague"],
  ["丹麥", "首都大區", "哥本哈根", "Europe/Copenhagen"],
  ["丹麥", "中日德蘭大區", "奧胡斯", "Europe/Copenhagen"],
  ["丹麥", "北日德蘭大區", "奧爾堡", "Europe/Copenhagen"],
  ["丹麥", "西蘭大區", "羅斯基勒", "Europe/Copenhagen"],
  ["丹麥", "南丹麥大區", "奧登斯", "Europe/Copenhagen"],
  ["丹麥", "格陵蘭島西部", "努克", "America/Godthab"],
  ["丹麥", "格陵蘭島東部", "伊圖科托米特", "America/Scoresbysund"],
  ["丹麥", "格陵蘭島北部", "卡納克", "America/Thule"],
  ["丹麥", "法羅群島", "托爾斯港", "Atlantic/Faroe"],
  ["吉布地", "吉布地共和國", "吉布地市", "Africa/Djibouti"],
  ["多米尼克", "多米尼克共和國", "羅索", "America/Dominica"],
  ["多明尼加", "多明尼加共和國", "聖多明哥", "America/Santo_Domingo"],
  ["東帝汶", "東帝汶民主共和國", "狄力", "Asia/Dili"],
  ["埃及", "埃及阿拉伯共和國", "開羅", "Africa/Cairo"],
  ["薩爾瓦多", "薩爾瓦多共和國", "聖薩爾瓦多", "America/El_Salvador"],
  ["赤道幾內亞", "赤道幾內亞共和國", "馬拉博", "Africa/Malabo"],
  ["厄利垂亞", "厄利垂亞國", "阿斯馬拉", "Africa/Asmara"],
  ["愛沙尼亞", "愛沙尼亞共和國", "塔林", "Europe/Tallinn"],
  ["衣索比亞", "衣索比亞聯邦民主共和國", "阿迪斯阿貝巴", "Africa/Addis_Ababa"],
  ["厄瓜多共和國", "加拉帕戈斯省", "巴克里索莫雷諾港", "Pacific/Galapagos"],
  ["厄瓜多共和國", "阿蘇艾省", "昆卡", "America/Guayaquil"],
  ["厄瓜多共和國", "玻利瓦爾省", "瓜蘭達", "America/Guayaquil"],
  ["厄瓜多共和國", "卡尼亞爾省", "阿索格斯", "America/Guayaquil"],
  ["厄瓜多共和國", "卡爾奇省", "圖爾坎", "America/Guayaquil"],
  ["厄瓜多共和國", "欽博拉索省", "里奧班巴", "America/Guayaquil"],
  ["厄瓜多共和國", "科托帕希省", "拉塔昆加", "America/Guayaquil"],
  ["厄瓜多共和國", "埃爾奧羅省", "馬查拉", "America/Guayaquil"],
  ["厄瓜多共和國", "艾斯美拉達斯省", "艾斯美拉達斯", "America/Guayaquil"],
  ["厄瓜多共和國", "瓜亞斯省", "瓜亞基爾", "America/Guayaquil"],
  ["厄瓜多共和國", "因巴布拉省", "伊瓦拉", "America/Guayaquil"],
  ["厄瓜多共和國", "洛哈省", "洛哈", "America/Guayaquil"],
  ["厄瓜多共和國", "洛斯里奧斯省", "巴巴奧約", "America/Guayaquil"],
  ["厄瓜多共和國", "馬納比省", "波托維耶霍", "America/Guayaquil"],
  ["厄瓜多共和國", "莫羅納-聖地亞哥省", "馬卡斯", "America/Guayaquil"],
  ["厄瓜多共和國", "納波省", "特納", "America/Guayaquil"],
  [
    "厄瓜多共和國",
    "奧雷亞納省",
    "法蘭西斯科·德·奧雷亞納港",
    "America/Guayaquil",
  ],
  ["厄瓜多共和國", "帕斯塔薩省", "普約", "America/Guayaquil"],
  ["厄瓜多共和國", "皮欽查省", "基多", "America/Guayaquil"],
  ["厄瓜多共和國", "聖埃倫娜省", "聖埃倫娜", "America/Guayaquil"],
  [
    "厄瓜多共和國",
    "聖多明哥-德洛斯查奇拉斯省",
    "聖多明哥",
    "America/Guayaquil",
  ],
  ["厄瓜多共和國", "蘇昆比奧斯省", "新洛哈", "America/Guayaquil"],
  ["厄瓜多共和國", "通古拉瓦省", "安巴托", "America/Guayaquil"],
  ["厄瓜多共和國", "薩莫拉-欽奇佩省", "薩莫拉", "America/Guayaquil"],
  ["法國", "奧弗涅-羅納-阿爾卑斯大區", "里昂（Lyon）", "Europe/Paris"],
  ["法國", "布列塔尼大區", "雷恩（Rennes）", "Europe/Paris"],
  ["法國", "勃艮第-弗朗什-孔泰大區", "第戎（Dijon）", "Europe/Paris"],
  ["法國", "中央-盧瓦爾河谷大區", "奧爾良（Orléans）", "Europe/Paris"],
  ["法國", "大東部大區", "斯特拉斯堡（Strasbourg）", "Europe/Paris"],
  ["法國", "法蘭西島大區", "巴黎（Paris）", "Europe/Paris"],
  ["法國", "上法蘭西大區", "里爾（Lille）", "Europe/Paris"],
  ["法國", "諾曼第大區", "魯昂（Rouen）", "Europe/Paris"],
  ["法國", "新阿基坦大區", "波爾多（Bordeaux）", "Europe/Paris"],
  ["法國", "奧克西塔尼大區", "圖盧茲（Toulouse）", "Europe/Paris"],
  ["法國", "盧瓦爾河地區大區", "南特（Nantes）", "Europe/Paris"],
  [
    "法國",
    "普羅旺斯-阿爾卑斯-藍色海岸大區",
    "馬賽（Marseille）",
    "Europe/Paris",
  ],
  ["法國", "科西嘉大區", "阿雅克肖（Ajaccio）", "Europe/Paris"],
  ["法國", "法屬圭亞那", "卡宴", "America/Cayenne"],
  ["法國", "法屬波利尼西亞", "帕皮提", "Pacific/Tahiti"],
  ["法國", "法屬波利尼西亞", "馬克薩斯群島", "Pacific/Marquesas"],
  ["法國", "法屬波利尼西亞", "甘比爾群島", "Pacific/Gambier"],
  ["法國", "瓜德羅普", "巴斯特爾", "America/Guadeloupe"],
  ["法國", "馬提尼克", "法蘭西堡", "America/Martinique"],
  ["法國", "馬約特", "馬穆楚", "Indian/Mayotte"],
  ["法國", "新喀里多尼亞", "努美阿", "Pacific/Noumea"],
  ["法國", "留尼汪", "聖但尼", "Indian/Reunion"],
  ["法國", "聖巴托洛繆", "居斯塔維亞", "America/St_Barthelemy"],
  ["法國", "法屬聖馬丁", "馬里戈特", "America/Marigot"],
  ["法國", "聖皮埃爾和密克隆群島", "聖皮埃爾", "America/Miquelon"],
  ["法國", "瓦利斯和富圖納", "馬塔烏圖", "Pacific/Wallis"],
  ["法國", "法屬南部和南極領地", "阿姆斯特丹島", "Indian/Antananarivo"],
  ["法國", "法屬南部和南極領地", "克羅澤群島", "Indian/Cocos"],
  ["法國", "法屬南部和南極領地", "克爾格倫群島", "Indian/Kerguelen"],
  ["法國", "法屬南部和南極領地", "聖保羅和阿姆斯特丹群島", "Indian/Reunion"],
  ["法國", "法屬南部和南極領地", "南極洲阿黛利地", "Antarctica/DumontDUrville"],
  ["斐濟", "斐濟共和國", "蘇瓦", "Pacific/Fiji"],
  ["芬蘭", "芬蘭共和國", "赫爾辛基", "Europe/Helsinki"],
  ["加彭", "加彭共和國", "自由市", "Africa/Libreville"],
  ["甘比亞", "甘比亞共和國", "班竹", "Africa/Banjul"],
  ["喬治亞", "喬治亞", "特比利西", "Asia/Tbilisi"],
  ["德國", "柏林市", "柏林", "Europe/Berlin"],
  ["德國", "巴登符騰堡邦", "斯圖加特", "Europe/Berlin"],
  ["德國", "巴伐利亞邦", "慕尼黑", "Europe/Berlin"],
  ["德國", "布蘭登堡邦", "波茲坦", "Europe/Berlin"],
  ["德國", "黑森邦", "威斯巴登", "Europe/Berlin"],
  ["德國", "麥克倫堡-佛波門邦", "施威林", "Europe/Berlin"],
  ["德國", "下薩克森邦", "漢諾威", "Europe/Berlin"],
  ["德國", "北萊茵-西伐利亞邦", "杜塞道夫", "Europe/Berlin"],
  ["德國", "萊茵蘭-法爾茲邦", "美因茲", "Europe/Berlin"],
  ["德國", "薩爾蘭邦", "薩爾布魯根", "Europe/Berlin"],
  ["德國", "薩克森邦", "德勒斯登", "Europe/Berlin"],
  ["德國", "薩克森-安哈特邦", "馬德堡", "Europe/Berlin"],
  ["德國", "什列斯威-霍爾斯坦邦", "基爾", "Europe/Berlin"],
  ["德國", "圖林根邦", "艾福特", "Europe/Berlin"],
  ["德國", "漢堡市", "漢堡", "Europe/Berlin"],
  ["德國", "不來梅市", "不來梅", "Europe/Berlin"],
  ["德國", "布辛根飛地", "布辛根", "Europe/Busingen"],
  ["迦納", "迦納共和國", "阿克西", "Africa/Accra"],
  ["希臘", "希臘共和國", "雅典", "Europe/Athens"],
  ["格瑞納達", "格瑞納達", "聖喬治", "America/Grenada"],
  ["瓜地馬拉", "瓜地馬拉共和國", "瓜地馬拉市", "America/Guatemala"],
  ["幾內亞", "幾內亞共和國", "科納克里", "Africa/Conakry"],
  ["幾內亞比索", "幾內亞比索共和國", "比索", "Africa/Bissau"],
  ["蓋亞那", "蓋亞那合作共和國", "喬治敦", "America/Guyana"],
  ["哈薩克共和國", "阿特勞州", "阿特勞", "Asia/Atyrau"],
  ["哈薩克共和國", "西哈薩克斯坦州", "烏拉爾", "Asia/Oral"],
  ["哈薩克共和國", "曼吉斯套州", "阿克套", "Asia/Aqtau"],
  ["哈薩克共和國", "阿克托別州", "阿克托別", "Asia/Aqtobe"],
  ["哈薩克共和國", "克孜勒奧爾達州", "克孜勒奧爾達", "Asia/Qyzylorda"],
  ["哈薩克共和國", "阿斯塔納市", "阿斯塔納", "Asia/Almaty"],
  ["哈薩克共和國", "阿拉木圖市", "阿拉木圖", "Asia/Almaty"],
  ["哈薩克共和國", "奇姆肯特市", "奇姆肯特", "Asia/Almaty"],
  ["哈薩克共和國", "阿克莫拉州", "科克舍套", "Asia/Almaty"],
  ["哈薩克共和國", "阿拉木圖州", "庫納耶夫", "Asia/Almaty"],
  ["哈薩克共和國", "江布爾州", "塔拉茲", "Asia/Almaty"],
  ["哈薩克共和國", "卡拉干達州", "卡拉干達", "Asia/Almaty"],
  ["哈薩克共和國", "科斯塔奈州", "科斯塔奈", "Asia/Almaty"],
  ["哈薩克共和國", "巴甫洛達爾州", "巴甫洛達爾", "Asia/Almaty"],
  ["哈薩克共和國", "北哈薩克斯坦州", "彼得羅巴甫爾", "Asia/Almaty"],
  ["哈薩克共和國", "東哈薩克斯坦州", "厄斯克門", "Asia/Almaty"],
  ["哈薩克共和國", "突厥斯坦州", "突厥斯坦", "Asia/Almaty"],
  ["哈薩克共和國", "傑特蘇州", "塔爾迪庫爾干", "Asia/Almaty"],
  ["哈薩克共和國", "阿拜州", "塞梅伊", "Asia/Almaty"],
  ["哈薩克共和國", "烏勒套州", "傑茲卡茲甘", "Asia/Almaty"],
  ["荷蘭", "阿魯巴", "奧腓士塔德（Oranjestad）", "America/Aruba"],
  ["荷蘭", "庫拉索", "威廉斯塔德（Willemstad）", "America/Curacao"],
  ["荷蘭", "荷屬聖馬丁", "菲利普斯堡（Philipsburg）", "America/Curacao"],
  ["荷蘭", "博奈爾", "克拉倫代克（Kralendijk）", "America/Kralendijk"],
  ["荷蘭", "聖尤斯特歇斯", "奧腓士城（Oranjestad）", "America/Kralendijk"],
  ["荷蘭", "薩巴", "鮑特姆（The Bottom）", "America/Kralendijk"],
  ["荷蘭", "弗里斯蘭省", "呂伐登（Leeuwarden）", "Europe/Amsterdam"],
  ["荷蘭", "格羅寧根省", "格羅寧根（Groningen）", "Europe/Amsterdam"],
  ["荷蘭", "德倫特省", "阿森（Assen）", "Europe/Amsterdam"],
  ["荷蘭", "上艾瑟爾省", "兹沃勒（Zwolle）", "Europe/Amsterdam"],
  ["荷蘭", "海爾德蘭省", "阿納姆（Arnhem）", "Europe/Amsterdam"],
  ["荷蘭", "烏特勒支省", "烏特勒支（Utrecht）", "Europe/Amsterdam"],
  ["荷蘭", "北荷蘭省", "阿姆斯特丹（Amsterdam）", "Europe/Amsterdam"],
  ["荷蘭", "南荷蘭省", "海牙（Den Haag）", "Europe/Amsterdam"],
  ["荷蘭", "澤蘭省", "米德爾堡（Middelburg）", "Europe/Amsterdam"],
  ["荷蘭", "北布拉班特省", "斯海爾托亨博思（Den Bosch）", "Europe/Amsterdam"],
  ["荷蘭", "林堡省", "馬斯特里赫特（Maastricht）", "Europe/Amsterdam"],
  ["荷蘭", "弗萊福蘭省", "萊利斯塔德（Lelystad）", "Europe/Amsterdam"],
  ["海地", "海地共和國", "太子港", "America/Port-au-Prince"],
  ["宏都拉斯", "宏都拉斯共和國", "德古西加巴", "America/Tegucigalpa"],
  ["匈牙利", "匈牙利", "布達佩斯", "Europe/Budapest"],
  ["印尼", "巴布亞省 (Papua)", "查亞普拉 (Jayapura)", "Asia/Jayapura"],
  ["印尼", "巴布亞高地省 (Highland Papua)", "瓦梅納 (Wamena)", "Asia/Jayapura"],
  ["印尼", "南巴布亞省 (South Papua)", "梅拉烏克 (Merauke)", "Asia/Jayapura"],
  ["印尼", "西巴布亞省 (West Papua)", "納比雷 (Nabire)", "Asia/Jayapura"],
  ["印尼", "北馬魯古省 (North Maluku)", "特爾納特 (Ternate)", "Asia/Jayapura"],
  ["印尼", "馬魯古省 (Maluku)", "安汶 (Ambon)", "Asia/Jayapura"],
  [
    "印尼",
    "西巴布亞新省 (Southwest Papua)",
    "納比雷 (Nabire)",
    "Asia/Jayapura",
  ],
  [
    "印尼",
    "東努沙登加拉省 (East Nusa Tenggara)",
    "古邦 (Kupang)",
    "Asia/Makassar",
  ],
  [
    "印尼",
    "西努沙登加拉省 (West Nusa Tenggara)",
    "馬塔蘭 (Mataram)",
    "Asia/Makassar",
  ],
  ["印尼", "巴厘省 (Bali)", "登帕薩 (Denpasar)", "Asia/Makassar"],
  [
    "印尼",
    "南蘇拉威西省 (South Sulawesi)",
    "望加錫 (Makassar)",
    "Asia/Makassar",
  ],
  ["印尼", "中蘇拉威西省 (Central Sulawesi)", "帕盧 (Palu)", "Asia/Makassar"],
  [
    "印尼",
    "東南蘇拉威西省 (Southeast Sulawesi)",
    "肯達里 (Kendari)",
    "Asia/Makassar",
  ],
  ["印尼", "北蘇拉威西省 (North Sulawesi)", "萊克 (Manado)", "Asia/Makassar"],
  ["印尼", "西蘇拉威西省 (West Sulawesi)", "馬穆朱 (Mamuju)", "Asia/Makassar"],
  ["印尼", "戈龍塔洛省 (Gorontalo)", "戈龍塔洛 (Gorontalo)", "Asia/Makassar"],
  [
    "印尼",
    "東加里曼丹省 (East Kalimantan)",
    "三馬林達 (Samarinda)",
    "Asia/Makassar",
  ],
  [
    "印尼",
    "北加里曼丹省 (North Kalimantan)",
    "塔拉坎 (Tarakan)",
    "Asia/Makassar",
  ],
  [
    "印尼",
    "南加里曼丹省 (South Kalimantan)",
    "班加爾馬辛 (Banjarmasin)",
    "Asia/Makassar",
  ],
  [
    "印尼",
    "中加里曼丹省 (Central Kalimantan)",
    "帕朗卡拉亞 (Palangka Raya)",
    "Asia/Makassar",
  ],
  [
    "印尼",
    "西加里曼丹省 (West Kalimantan)",
    "坤甸 (Pontianak)",
    "Asia/Pontianak",
  ],
  ["印尼", "廖內省 (Riau)", "北干巴魯 (Pekanbaru)", "Asia/Jakarta"],
  ["印尼", "廖內群島省 (Riau Islands)", "巴淡島 (Batam)", "Asia/Jakarta"],
  ["印尼", "雅加達首都特區 (Jakarta)", "雅加達 (Jakarta)", "Asia/Jakarta"],
  ["印尼", "萬丹省 (Banten)", "斯朗 (Serang)", "Asia/Jakarta"],
  ["印尼", "西爪哇省 (West Java)", "萊姆邦 (Bandung)", "Asia/Jakarta"],
  ["印尼", "中爪哇省 (Central Java)", "三寶瓏 (Semarang)", "Asia/Jakarta"],
  ["印尼", "東爪哇省 (East Java)", "泗水 (Surabaya)", "Asia/Jakarta"],
  ["印尼", "日惹特區 (Yogyakarta)", "日惹 (Yogyakarta)", "Asia/Jakarta"],
  ["印尼", "楠榜省 (Lampung)", "井里汶 (Bandar Lampung)", "Asia/Jakarta"],
  ["印尼", "明古魯省 (Bengkulu)", "明古魯 (Bengkulu)", "Asia/Jakarta"],
  ["印尼", "占碑省 (Jambi)", "占碑 (Jambi)", "Asia/Jakarta"],
  ["印尼", "南蘇門答臘省 (South Sumatra)", "巨港 (Palembang)", "Asia/Jakarta"],
  ["印尼", "西蘇門答臘省 (West Sumatra)", "巴東 (Padang)", "Asia/Jakarta"],
  ["印尼", "北蘇門答臘省 (North Sumatra)", "棉蘭 (Medan)", "Asia/Jakarta"],
  ["印尼", "亞齊特區 (Aceh)", "班達亞齊 (Banda Aceh)", "Asia/Jakarta"],
  ["冰島", "冰島", "雷克雅未克", "Atlantic/Reykjavik"],
  ["印度", "印度共和國", "新德里", "Asia/Kolkata"],
  ["伊朗", "伊朗伊斯蘭共和國", "德黑蘭", "Asia/Tehran"],
  ["伊拉克", "伊拉克共和國", "巴格達", "Asia/Baghdad"],
  ["愛爾蘭", "愛爾蘭共和國", "都柏林", "Europe/Dublin"],
  ["以色列", "以色列國", "耶路撒冷", "Asia/Jerusalem"],
  ["義大利", "義大利共和國", "羅馬", "Europe/Rome"],
  ["象牙海岸", "象牙海岸共和國", "阿比尚", "Africa/Abidjan"],
  ["牙買加", "牙買加", "金斯頓", "America/Jamaica"],
  ["日本", "北海道", "北海道", "Asia/Tokyo"],
  ["日本", "東北地方", "青森縣", "Asia/Tokyo"],
  ["日本", "東北地方", "岩手縣", "Asia/Tokyo"],
  ["日本", "東北地方", "宮城縣", "Asia/Tokyo"],
  ["日本", "東北地方", "秋田縣", "Asia/Tokyo"],
  ["日本", "東北地方", "山形縣", "Asia/Tokyo"],
  ["日本", "東北地方", "福島縣", "Asia/Tokyo"],
  ["日本", "關東地方", "茨城縣", "Asia/Tokyo"],
  ["日本", "關東地方", "栃木縣", "Asia/Tokyo"],
  ["日本", "關東地方", "群馬縣", "Asia/Tokyo"],
  ["日本", "關東地方", "埼玉縣", "Asia/Tokyo"],
  ["日本", "關東地方", "千葉縣", "Asia/Tokyo"],
  ["日本", "關東地方", "東京都", "Asia/Tokyo"],
  ["日本", "關東地方", "神奈川縣", "Asia/Tokyo"],
  ["日本", "中部地方（甲信越）", "新潟縣", "Asia/Tokyo"],
  ["日本", "中部地方（甲信越）", "山梨縣", "Asia/Tokyo"],
  ["日本", "中部地方（甲信越）", "長野縣", "Asia/Tokyo"],
  ["日本", "中部地方（北陸）", "富山縣", "Asia/Tokyo"],
  ["日本", "中部地方（北陸）", "石川縣", "Asia/Tokyo"],
  ["日本", "中部地方（北陸）", "福井縣", "Asia/Tokyo"],
  ["日本", "中部地方（東海）", "岐阜縣", "Asia/Tokyo"],
  ["日本", "中部地方（東海）", "靜岡縣", "Asia/Tokyo"],
  ["日本", "中部地方（東海）", "愛知縣", "Asia/Tokyo"],
  ["日本", "近畿地方", "三重縣", "Asia/Tokyo"],
  ["日本", "近畿地方", "滋賀縣", "Asia/Tokyo"],
  ["日本", "近畿地方", "京都府", "Asia/Tokyo"],
  ["日本", "近畿地方", "大阪府", "Asia/Tokyo"],
  ["日本", "近畿地方", "兵庫縣", "Asia/Tokyo"],
  ["日本", "近畿地方", "奈良縣", "Asia/Tokyo"],
  ["日本", "近畿地方", "和歌山縣", "Asia/Tokyo"],
  ["日本", "中國地方", "鳥取縣", "Asia/Tokyo"],
  ["日本", "中國地方", "島根縣", "Asia/Tokyo"],
  ["日本", "中國地方", "岡山縣", "Asia/Tokyo"],
  ["日本", "中國地方", "廣島縣", "Asia/Tokyo"],
  ["日本", "中國地方", "山口縣", "Asia/Tokyo"],
  ["日本", "四國地方", "德島縣", "Asia/Tokyo"],
  ["日本", "四國地方", "香川縣", "Asia/Tokyo"],
  ["日本", "四國地方", "愛媛縣", "Asia/Tokyo"],
  ["日本", "四國地方", "高知縣", "Asia/Tokyo"],
  ["日本", "九州地方", "福岡縣", "Asia/Tokyo"],
  ["日本", "九州地方", "佐賀縣", "Asia/Tokyo"],
  ["日本", "九州地方", "長崎縣", "Asia/Tokyo"],
  ["日本", "九州地方", "熊本縣", "Asia/Tokyo"],
  ["日本", "九州地方", "大分縣", "Asia/Tokyo"],
  ["日本", "九州地方", "宮崎縣", "Asia/Tokyo"],
  ["日本", "九州地方", "鹿兒島縣", "Asia/Tokyo"],
  ["日本", "九州地方", "沖繩縣", "Asia/Tokyo"],
  ["約旦", "約旦哈希米王國", "安曼", "Asia/Amman"],
  [
    "吉里巴斯",
    "萊恩群島 (Line Islands)",
    "克里斯馬斯島 (Kiritimati)",
    "Pacific/Kiritimati",
  ],
  [
    "吉里巴斯",
    "鳳凰群島 (Phoenix Islands)",
    "坦加羅亞 (Tangatabu)",
    "Pacific/Enderbury",
  ],
  [
    "吉里巴斯",
    "吉爾伯特群島 (Gilbert Islands)",
    "塔拉瓦 (Tarawa)",
    "Pacific/Tarawa",
  ],
  ["肯亞", "肯亞共和國", "奈洛比", "Africa/Nairobi"],
  ["北韓", "朝鮮民主主義人民共和國", "平壤", "Asia/Pyongyang"],
  ["南韓", "江原", "江原特別自治道", "Asia/Seoul"],
  ["南韓", "京畿", "首爾", "Asia/Seoul"],
  ["南韓", "京畿", "仁川市", "Asia/Seoul"],
  ["南韓", "京畿", "京畿道", "Asia/Seoul"],
  ["南韓", "忠清", "忠清北道", "Asia/Seoul"],
  ["南韓", "忠清", "忠清南道", "Asia/Seoul"],
  ["南韓", "忠清", "世宗市", "Asia/Seoul"],
  ["南韓", "忠清", "大田", "Asia/Seoul"],
  ["南韓", "慶尚", "慶尚北道", "Asia/Seoul"],
  ["南韓", "慶尚", "慶尚南道", "Asia/Seoul"],
  ["南韓", "慶尚", "大邱市", "Asia/Seoul"],
  ["南韓", "慶尚", "蔚山", "Asia/Seoul"],
  ["南韓", "慶尚", "釜山", "Asia/Seoul"],
  ["南韓", "全羅", "全北特別自治道", "Asia/Seoul"],
  ["南韓", "全羅", "全羅南道", "Asia/Seoul"],
  ["南韓", "全羅", "光州", "Asia/Seoul"],
  ["南韓", "濟州", "濟州道", "Asia/Seoul"],
  ["科威特", "科威特國", "科威特城", "Asia/Kuwait"],
  ["科索沃", "科索沃共和國", "普里什蒂納", "Europe/Belgrade"],
  ["寮國", "寮人民民主共和國", "永珍", "Asia/Vientiane"],
  ["拉脫維亞", "拉脫維亞共和國", "里加", "Europe/Riga"],
  ["黎巴嫩", "黎巴嫩共和國", "貝魯特", "Asia/Beirut"],
  ["賴索托", "賴索托王國", "馬塞魯", "Africa/Maseru"],
  ["賴比瑞亞", "賴比瑞亞共和國", "蒙羅維亞", "Africa/Monrovia"],
  ["利比亞", "利比亞國", "的黎波里", "Africa/Tripoli"],
  ["列支敦斯登", "列支敦斯登侯國", "瓦杜茲", "Europe/Vaduz"],
  ["立陶宛", "立陶宛共和國", "維爾紐斯", "Europe/Vilnius"],
  ["盧森堡", "盧森堡大公國", "盧森堡市", "Europe/Luxembourg"],
  ["墨西哥", "金塔納羅奧州 (Quintana Roo)", "坎昆 (Cancún)", "America/Cancun"],
  [
    "墨西哥",
    "下加利福尼亞州 (Baja California)",
    "墨西卡利 (Mexicali)",
    "America/Tijuana",
  ],
  [
    "墨西哥",
    "南下加利福尼亞州 (Baja California Sur)",
    "拉巴斯 (La Paz)",
    "America/Mazatlan",
  ],
  [
    "墨西哥",
    "索諾拉州 (Sonora)",
    "埃莫西約 (Hermosillo)",
    "America/Hermosillo",
  ],
  ["墨西哥", "奇瓦瓦州 (Chihuahua)", "奇瓦瓦 (Chihuahua)", "America/Chihuahua"],
  ["墨西哥", "杜蘭戈州 (Durango)", "杜蘭戈 (Durango)", "America/Monterrey"],
  [
    "墨西哥",
    "薩卡特卡斯州 (Zacatecas)",
    "薩卡特卡斯 (Zacatecas)",
    "America/Monterrey",
  ],
  [
    "墨西哥",
    "聖路易斯波托西州 (San Luis Potosí)",
    "聖路易斯波托西 (San Luis Potosí)",
    "America/Mexico_City",
  ],
  [
    "墨西哥",
    "阿瓜斯卡連特斯州 (Aguascalientes)",
    "阿瓜斯卡連特斯 (Aguascalientes)",
    "America/Mexico_City",
  ],
  [
    "墨西哥",
    "科阿韋拉州 (Coahuila)",
    "蒙克洛瓦 (Monclova)",
    "America/Monterrey",
  ],
  [
    "墨西哥",
    "塔毛利帕斯州 (Tamaulipas)",
    "塔毛利帕斯 (Tamaulipas)",
    "America/Matamoros",
  ],
  [
    "墨西哥",
    "新萊昂州 (Nuevo León)",
    "蒙特雷 (Monterrey)",
    "America/Monterrey",
  ],
  [
    "墨西哥",
    "哈利斯科州 (Jalisco)",
    "瓜達拉哈拉 (Guadalajara)",
    "America/Mexico_City",
  ],
  ["墨西哥", "納亞里特州 (Nayarit)", "特皮克 (Tepic)", "America/Mazatlan"],
  ["墨西哥", "錫那羅亞州 (Sinaloa)", "庫利亞坎 (Culiacán)", "America/Mazatlan"],
  [
    "墨西哥",
    "格雷羅州 (Guerrero)",
    "阿卡普爾科 (Acapulco)",
    "America/Mexico_City",
  ],
  [
    "墨西哥",
    "米卻肯州 (Michoacán)",
    "莫雷利亞 (Morelia)",
    "America/Mexico_City",
  ],
  [
    "墨西哥",
    "特拉斯卡拉州 (Tlaxcala)",
    "特拉斯卡拉 (Tlaxcala)",
    "America/Mexico_City",
  ],
  ["墨西哥", "普埃布拉州 (Puebla)", "普埃布拉 (Puebla)", "America/Mexico_City"],
  [
    "墨西哥",
    "韋拉克魯斯州 (Veracruz)",
    "韋拉克魯斯 (Veracruz)",
    "America/Mexico_City",
  ],
  ["墨西哥", "伊達爾戈州 (Hidalgo)", "帕丘卡 (Pachuca)", "America/Mexico_City"],
  [
    "墨西哥",
    "克雷塔羅州 (Querétaro)",
    "克雷塔羅 (Querétaro)",
    "America/Mexico_City",
  ],
  ["墨西哥", "墨西哥州 (México)", "托盧卡 (Toluca)", "America/Mexico_City"],
  [
    "墨西哥",
    "聯邦區 (Ciudad de México)",
    "墨西哥城 (Mexico City)",
    "America/Mexico_City",
  ],
  [
    "墨西哥",
    "瓜納華托州 (Guanajuato)",
    "瓜納華托 (Guanajuato)",
    "America/Mexico_City",
  ],
  ["墨西哥", "科利馬州 (Colima)", "科利馬 (Colima)", "America/Mexico_City"],
  [
    "墨西哥",
    "莫雷洛斯州 (Morelos)",
    "庫埃納瓦卡 (Cuernavaca)",
    "America/Mexico_City",
  ],
  ["墨西哥", "坎佩切州 (Campeche)", "坎佩切 (Campeche)", "America/Merida"],
  ["墨西哥", "尤卡坦州 (Yucatán)", "梅里達 (Mérida)", "America/Merida"],
  [
    "墨西哥",
    "恰帕斯州 (Chiapas)",
    "圖斯特拉古鐵雷斯 (Tuxtla Gutiérrez)",
    "America/Mexico_City",
  ],
  [
    "墨西哥",
    "塔巴斯科州 (Tabasco)",
    "比亞埃爾莫薩 (Villahermosa)",
    "America/Mexico_City",
  ],
  [
    "墨西哥",
    "克雷塔羅州 (Querétaro)",
    "克雷塔羅 (Querétaro)",
    "America/Mexico_City",
  ],
  ["密克羅西亞", "科斯雷州", "托福爾（Tofol）", "Pacific/Kosrae"],
  ["密克羅西亞", "波納佩州", "帕利基爾（Palikir）", "Pacific/Pohnpei"],
  ["密克羅西亞", "楚克州", "維諾（Weno）", "Pacific/Chuuk"],
  ["密克羅西亞", "雅浦州", "科洛尼亞（Colonia）", "Pacific/Chuuk"],
  ["蒙古國", "巴彥烏列蓋省", "烏列蓋", "Asia/Hovd"],
  ["蒙古國", "科布多省", "科布多", "Asia/Hovd"],
  ["蒙古國", "烏布蘇省", "烏蘭固木", "Asia/Hovd"],
  ["蒙古國", "戈壁阿爾泰省", "阿爾泰", "Asia/Hovd"],
  ["蒙古國", "扎布汗省", "烏里雅蘇臺", "Asia/Hovd"],
  ["蒙古國", "後杭愛省", "車車爾勒格", "Asia/Hovd"],
  ["蒙古國", "烏蘭巴托市", "烏蘭巴托", "Asia/Ulaanbaatar"],
  ["蒙古國", "中央省", "宗莫德", "Asia/Ulaanbaatar"],
  ["蒙古國", "色楞格省", "蘇赫巴托爾", "Asia/Ulaanbaatar"],
  ["蒙古國", "達爾汗烏拉省", "達爾汗", "Asia/Ulaanbaatar"],
  ["蒙古國", "鄂爾渾省", "額爾登特", "Asia/Ulaanbaatar"],
  ["蒙古國", "布爾干省", "布爾干", "Asia/Ulaanbaatar"],
  ["蒙古國", "肯特省", "溫都爾汗", "Asia/Ulaanbaatar"],
  ["蒙古國", "蘇赫巴托爾省", "西烏爾特", "Asia/Ulaanbaatar"],
  ["蒙古國", "東方省", "喬巴山", "Asia/Ulaanbaatar"],
  ["蒙古國", "庫蘇古爾省", "木倫", "Asia/Ulaanbaatar"],
  ["蒙古國", "前杭愛省", "阿爾拜赫雷", "Asia/Ulaanbaatar"],
  ["蒙古國", "巴彥洪戈爾省", "巴彥洪戈爾", "Asia/Ulaanbaatar"],
  ["蒙古國", "南戈壁省", "達蘭扎達嘎德", "Asia/Ulaanbaatar"],
  ["蒙古國", "中戈壁省", "曼達勒戈壁", "Asia/Ulaanbaatar"],
  ["蒙古國", "東戈壁省", "賽音山達", "Asia/Ulaanbaatar"],
  ["蒙古國", "戈壁蘇木貝爾省", "喬伊爾", "Asia/Ulaanbaatar"],
  ["北馬其頓", "北馬其頓共和國", "史高比耶", "Europe/Skopje"],
  ["馬達加斯加", "馬達加斯加共和國", "安塔那那利佛", "Indian/Antananarivo"],
  ["馬拉威", "馬拉威共和國", "布蘭泰爾", "Africa/Blantyre"],
  ["馬來西亞", "雪蘭莪", "莎阿南", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "霹靂", "怡保", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "彭亨", "關丹", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "柔佛", "新山", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "吉打", "亞羅士打", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "吉蘭丹", "哥打峇魯", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "登嘉樓", "瓜拉登嘉樓", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "森美蘭", "芙蓉市", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "玻璃市", "加央", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "檳城", "喬治市", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "麻六甲", "麻六甲市", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "沙巴", "亞庇", "Asia/Kuching"],
  ["馬來西亞", "砂拉越", "古晉", "Asia/Kuching"],
  ["馬來西亞", "吉隆坡", "吉隆坡", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "布城", "布城", "Asia/Kuala_Lumpur"],
  ["馬來西亞", "納閩", "納閩", "Asia/Kuala_Lumpur"],
  ["馬爾地夫", "馬爾地夫共和國", "馬列", "Indian/Maldives"],
  ["馬利", "馬利共和國", "巴馬科", "Africa/Bamako"],
  ["馬爾他", "馬爾他共和國", "瓦勒他", "Europe/Malta"],
  ["馬紹爾群島", "馬紹爾群島共和國", "馬久羅", "Pacific/Majuro"],
  ["茅利塔尼亞", "茅利塔尼亞伊斯蘭共和國", "努瓦克肖特", "Africa/Nouakchott"],
  ["模里西斯", "模里西斯共和國", "路易士港", "Indian/Mauritius"],
  ["摩爾多瓦", "摩爾多瓦共和國", "基西涅夫", "Europe/Chisinau"],
  ["摩納哥", "摩納哥侯國", "摩納哥城", "Europe/Monaco"],
  ["蒙特內哥羅", "蒙特內哥羅", "波德里查", "Europe/Podgorica"],
  ["摩洛哥", "摩洛哥王國", "卡薩布蘭卡", "Africa/Casablanca"],
  ["莫三比克", "莫三比克共和國", "馬布多", "Africa/Maputo"],
  ["緬甸", "緬甸聯邦共和國", "仰光", "Asia/Yangon"],
  ["紐西蘭", "紐埃", "阿洛菲", "Pacific/Niue"],
  ["紐西蘭", "庫克群島", "阿瓦魯阿", "Pacific/Rarotonga"],
  ["紐西蘭", "查塔姆群島", "瓦伊唐伊", "Pacific/Chatham"],
  ["紐西蘭", "北地", "旺阿雷", "Pacific/Auckland"],
  ["紐西蘭", "奧克蘭", "奧克蘭", "Pacific/Auckland"],
  ["紐西蘭", "懷卡托", "漢彌爾頓", "Pacific/Auckland"],
  ["紐西蘭", "普倫蒂灣", "陶朗加 (Tauranga)", "Pacific/Auckland"],
  ["紐西蘭", "吉斯伯恩", "吉斯伯恩", "Pacific/Auckland"],
  ["紐西蘭", "霍克灣", "納皮爾", "Pacific/Auckland"],
  ["紐西蘭", "塔拉那基", "新普利茅斯", "Pacific/Auckland"],
  ["紐西蘭", "馬納瓦圖-旺加努伊", "北帕默斯頓", "Pacific/Auckland"],
  ["紐西蘭", "惠靈頓", "惠靈頓", "Pacific/Auckland"],
  ["紐西蘭", "塔斯曼", "里士滿", "Pacific/Auckland"],
  ["紐西蘭", "尼爾森", "尼爾森", "Pacific/Auckland"],
  ["紐西蘭", "馬爾伯勒", "布倫亨", "Pacific/Auckland"],
  ["紐西蘭", "西岸", "格雷茅斯", "Pacific/Auckland"],
  ["紐西蘭", "坎特伯雷", "基督城", "Pacific/Auckland"],
  ["紐西蘭", "奧塔哥", "但尼丁", "Pacific/Auckland"],
  ["紐西蘭", "南地", "因弗卡吉爾", "Pacific/Auckland"],
  ["紐西蘭", "托克勞群島", "法考福", "Pacific/Fakaofo"],
  ["納米比亞", "納米比亞共和國", "溫荷克", "Africa/Windhoek"],
  ["諾魯", "諾魯共和國", "亞倫區", "Pacific/Nauru"],
  ["尼泊爾", "尼泊爾聯邦民主共和國", "加德滿都", "Asia/Kathmandu"],
  ["尼加拉瓜", "尼加拉瓜共和國", "馬納瓜", "America/Managua"],
  ["尼日", "尼日共和國", "尼阿美", "Africa/Niamey"],
  ["奈及利亞", "奈及利亞聯邦共和國", "阿布賈", "Africa/Lagos"],
  ["挪威", "挪威本土", "奧斯陸", "Europe/Oslo"],
  ["挪威", "挪威本土", "卑爾根", "Europe/Oslo"],
  ["挪威", "挪威本土", "特隆赫姆", "Europe/Oslo"],
  ["挪威", "挪威本土", "斯塔萬格", "Europe/Oslo"],
  ["挪威", "挪威本土", "特羅姆瑟", "Europe/Oslo"],
  ["挪威", "挪威本土", "博德", "Europe/Oslo"],
  ["挪威", "冷岸群島", "冷岸群島", "Arctic/Longyearbyen"],
  ["挪威", "揚馬延島", "揚馬延島", "Atlantic/Jan_Mayen"],
  ["阿曼", "阿曼蘇丹國", "馬斯喀特", "Asia/Muscat"],
  [
    "葡萄牙",
    "亞速爾自治區",
    "蓬塔德爾加達（Ponta Delgada）",
    "Atlantic/Azores",
  ],
  ["葡萄牙", "馬德拉自治區", "豐沙爾（Funchal）", "Atlantic/Madeira"],
  ["葡萄牙", "里斯本區", "里斯本（Lisbon）", "Europe/Lisbon"],
  ["葡萄牙", "波爾圖區", "波爾圖（Porto）", "Europe/Lisbon"],
  ["葡萄牙", "科英布拉區", "科英布拉（Coimbra）", "Europe/Lisbon"],
  ["葡萄牙", "維亞納堡區", "維亞納堡（Viana do Castelo）", "Europe/Lisbon"],
  ["葡萄牙", "布拉加區", "布拉加（Braga）", "Europe/Lisbon"],
  ["葡萄牙", "雷亞爾城區", "雷亞爾城（Vila Real）", "Europe/Lisbon"],
  ["葡萄牙", "布拉干薩區", "布拉干薩（Bragança）", "Europe/Lisbon"],
  ["葡萄牙", "瓜達區", "瓜達（Guarda）", "Europe/Lisbon"],
  ["葡萄牙", "萊里亞區", "萊里亞（Leiria）", "Europe/Lisbon"],
  ["葡萄牙", "阿威羅區", "阿威羅（Aveiro）", "Europe/Lisbon"],
  ["葡萄牙", "維塞烏區", "維塞烏（Viseu）", "Europe/Lisbon"],
  ["葡萄牙", "聖塔倫區", "聖塔倫（Santarém）", "Europe/Lisbon"],
  ["葡萄牙", "埃武拉區", "埃武拉（Évora）", "Europe/Lisbon"],
  ["葡萄牙", "法魯區", "法魯（Faro）", "Europe/Lisbon"],
  ["葡萄牙", "布朗庫堡區", "布朗庫堡（Castelo Branco）", "Europe/Lisbon"],
  ["葡萄牙", "波塔萊格雷區", "波塔萊格雷（Portalegre）", "Europe/Lisbon"],
  ["葡萄牙", "貝雅區", "貝雅（Beja）", "Europe/Lisbon"],
  ["葡萄牙", "塞圖巴爾區", "塞圖巴爾（Setúbal）", "Europe/Lisbon"],
  ["巴基斯坦", "巴基斯坦伊斯蘭共和國", "伊斯蘭堡", "Asia/Karachi"],
  ["帛琉", "帛琉共和國", "柯羅島", "Pacific/Palau"],
  ["巴拿馬", "巴拿馬共和國", "巴拿馬城", "America/Panama"],
  ["巴拉圭", "巴拉圭共和國", "亞松森", "America/Asuncion"],
  ["秘魯", "秘魯共和國", "利馬", "America/Lima"],
  ["菲律賓", "呂宋島", "馬尼拉", "Asia/Manila"],
  ["菲律賓", "呂宋島", "奎松市", "Asia/Manila"],
  ["菲律賓", "呂宋島", "碧瑤", "Asia/Manila"],
  ["菲律賓", "呂宋島", "納加市", "Asia/Manila"],
  ["菲律賓", "米沙鄢群島", "宿霧市", "Asia/Manila"],
  ["菲律賓", "米沙鄢群島", "伊洛伊洛市", "Asia/Manila"],
  ["菲律賓", "米沙鄢群島", "巴科洛德市", "Asia/Manila"],
  ["菲律賓", "民答那峨島", "達沃市", "Asia/Manila"],
  ["菲律賓", "民答那峨島", "卡加延德奧羅", "Asia/Manila"],
  ["菲律賓", "民答那峨島", "三寶顏市", "Asia/Manila"],
  ["波蘭", "波蘭共和國", "華沙", "Europe/Warsaw"],
  ["卡達", "卡達國", "杜哈", "Asia/Qatar"],
  ["俄羅斯", "加里寧格勒州", "加里寧格勒", "Europe/Kaliningrad"],
  ["俄羅斯", "別爾哥羅德州", "別爾哥羅德", "Europe/Moscow"],
  ["俄羅斯", "布良斯克州", "布良斯克", "Europe/Moscow"],
  ["俄羅斯", "達吉斯坦共和國", "馬哈奇卡拉", "Europe/Moscow"],
  ["俄羅斯", "列寧格勒州", "加特契納", "Europe/Moscow"],
  ["俄羅斯", "利佩茨克州", "利佩茨克", "Europe/Moscow"],
  ["俄羅斯", "莫斯科州", "莫斯科", "Europe/Moscow"],
  ["俄羅斯", "穆爾曼斯克州", "穆爾曼斯克", "Europe/Moscow"],
  ["俄羅斯", "涅涅茨自治區", "納里揚馬爾", "Europe/Moscow"],
  ["俄羅斯", "下諾夫哥羅德州", "下諾夫哥羅德", "Europe/Moscow"],
  ["俄羅斯", "諾夫哥羅德州", "大諾夫哥羅德", "Europe/Moscow"],
  ["俄羅斯", "奥廖爾州", "奥廖爾", "Europe/Moscow"],
  ["俄羅斯", "斯摩棱斯克州", "斯摩棱斯克", "Europe/Moscow"],
  ["俄羅斯", "坦波夫州", "坦波夫", "Europe/Moscow"],
  ["俄羅斯", "韃靼斯坦共和國", "喀山", "Europe/Moscow"],
  ["俄羅斯", "欽奇州", "欽奇", "Europe/Moscow"],
  ["俄羅斯", "卡盧加州", "卡盧加", "Europe/Moscow"],
  ["俄羅斯", "卡累利阿共和國", "彼得羅扎沃茨克", "Europe/Moscow"],
  ["俄羅斯", "卡爾梅克共和國", "埃利斯塔", "Europe/Moscow"],
  ["俄羅斯", "馬里埃爾共和國", "約什卡爾奧拉", "Europe/Moscow"],
  ["俄羅斯", "莫爾多瓦共和國", "薩蘭斯克", "Europe/Moscow"],
  ["俄羅斯", "克拉斯諾達爾邊疆區", "克拉斯諾達爾", "Europe/Moscow"],
  ["俄羅斯", "科米共和國", "瑟克特夫卡爾", "Europe/Moscow"],
  ["俄羅斯", "科斯特羅馬州", "科斯特羅馬", "Europe/Moscow"],
  ["俄羅斯", "薩馬拉州", "薩馬拉", "Europe/Samara"],
  ["俄羅斯", "阿斯特拉罕州", "阿斯特拉罕", "Europe/Samara"],
  ["俄羅斯", "薩拉托夫州", "薩拉托夫", "Europe/Samara"],
  ["俄羅斯", "烏德穆爾特共和國", "伊熱夫斯克", "Europe/Samara"],
  ["俄羅斯", "烏里揚諾夫斯克州", "烏里揚諾夫斯克", "Europe/Samara"],
  ["俄羅斯", "車里雅賓斯克州", "車里雅賓斯克", "Asia/Yekaterinburg"],
  ["俄羅斯", "巴什科爾托斯坦共和國", "烏法", "Asia/Yekaterinburg"],
  ["俄羅斯", "庫爾干州", "庫爾干", "Asia/Yekaterinburg"],
  ["俄羅斯", "奧倫堡州", "奧倫堡", "Asia/Yekaterinburg"],
  ["俄羅斯", "漢特-曼西自治區", "漢特-曼西斯克", "Asia/Yekaterinburg"],
  ["俄羅斯", "彼爾姆邊疆區", "彼爾姆", "Asia/Yekaterinburg"],
  ["俄羅斯", "斯維爾德洛夫斯克州", "葉卡捷琳堡", "Asia/Yekaterinburg"],
  ["俄羅斯", "秋明州", "秋明", "Asia/Yekaterinburg"],
  ["俄羅斯", "亞馬爾-涅涅茨自治區", "索斯諾戈爾斯克", "Asia/Yekaterinburg"],
  ["俄羅斯", "鄂木斯克州", "鄂木斯克", "Asia/Omsk"],
  ["俄羅斯", "新西伯利亞州", "新西伯利亞", "Asia/Novosibirsk"],
  ["俄羅斯", "阿爾泰共和國", "戈爾諾-阿爾泰斯克", "Asia/Barnaul"],
  ["俄羅斯", "阿爾泰邊疆區", "巴爾瑙爾", "Asia/Barnaul"],
  ["俄羅斯", "克拉斯諾亞爾斯克邊疆區", "克拉斯諾亞爾斯克", "Asia/Krasnoyarsk"],
  ["俄羅斯", "圖瓦共和國", "克孜勒", "Asia/Krasnoyarsk"],
  ["俄羅斯", "科麥羅沃州", "科麥羅沃", "Asia/Krasnoyarsk"],
  ["俄羅斯", "哈卡斯共和國", "阿巴坎", "Asia/Krasnoyarsk"],
  ["俄羅斯", "托木斯克州", "托木斯克", "Asia/Tomsk"],
  ["俄羅斯", "布里亞特共和國", "烏蘭烏德", "Asia/Irkutsk"],
  ["俄羅斯", "伊爾庫茨克州", "伊爾庫茨克", "Asia/Irkutsk"],
  ["俄羅斯", "阿穆爾州", "布拉戈維申斯克", "Asia/Yakutsk"],
  ["俄羅斯", "薩哈（雅庫特）共和國西部", "雅庫茨克", "Asia/Yakutsk"],
  ["俄羅斯", "外貝加爾邊疆區", "赤塔", "Asia/Yakutsk"],
  ["俄羅斯", "薩哈（雅庫特）共和國中部", "蒙阿", "Asia/Vladivostok"],
  ["俄羅斯", "猶太自治州", "比羅比詹", "Asia/Vladivostok"],
  ["俄羅斯", "哈巴羅夫斯克邊疆區", "哈巴羅夫斯克", "Asia/Vladivostok"],
  ["俄羅斯", "濱海邊疆區", "符拉迪沃斯托克", "Asia/Vladivostok"],
  ["俄羅斯", "馬加丹州", "馬加丹", "Asia/Magadan"],
  ["俄羅斯", "薩哈（雅庫特）共和國東部", "提克西", "Asia/Magadan"],
  ["俄羅斯", "薩哈林州", "南薩哈林斯克", "Asia/Magadan"],
  ["俄羅斯", "楚科奇自治區", "阿納德爾", "Asia/Anadyr"],
  ["俄羅斯", "堪察加邊疆區", "彼得羅巴甫洛夫斯克", "Asia/Kamchatka"],
  ["羅馬尼亞", "羅馬尼亞", "布加勒斯特", "Europe/Bucharest"],
  ["盧安達", "盧安達共和國", "基加利", "Africa/Kigali"],
  [
    "南非",
    "愛德華王子群島",
    "馬里昂島（Marion Island）",
    "Indian/Antananarivo",
  ],
  ["南非", "豪登省", "約翰尼斯堡", "Africa/Johannesburg"],
  ["南非", "西開普省", "開普敦", "Africa/Johannesburg"],
  ["南非", "東開普省", "伊麗莎白港", "Africa/Johannesburg"],
  ["南非", "夸祖魯-納塔爾省", "德爾班", "Africa/Johannesburg"],
  ["南非", "自由邦省", "布隆方丹", "Africa/Johannesburg"],
  ["南非", "北開普省", "金伯利", "Africa/Johannesburg"],
  ["南非", "西北省", "馬菲肯", "Africa/Johannesburg"],
  ["南非", "普馬蘭加省", "姆博馬貝拉", "Africa/Johannesburg"],
  ["南非", "林波波省", "波羅克瓦尼", "Africa/Johannesburg"],
  ["西班牙", "加那利群島", "拉斯帕爾馬斯", "Atlantic/Canary"],
  ["西班牙", "加利西亞", "聖地亞哥-德孔波斯特拉", "Europe/Madrid"],
  ["西班牙", "阿斯圖里亞斯", "奧維耶多", "Europe/Madrid"],
  ["西班牙", "坎塔布里亞", "桑坦德", "Europe/Madrid"],
  ["西班牙", "巴斯克", "畢爾包", "Europe/Madrid"],
  ["西班牙", "納瓦拉", "潘普洛納", "Europe/Madrid"],
  ["西班牙", "拉里奧哈", "洛格羅尼奧", "Europe/Madrid"],
  ["西班牙", "阿拉貢", "薩拉戈薩", "Europe/Madrid"],
  ["西班牙", "加泰羅尼亞", "巴塞隆納", "Europe/Madrid"],
  ["西班牙", "卡斯蒂利亞-雷昂", "巴利亞多利德", "Europe/Madrid"],
  ["西班牙", "馬德里", "馬德里", "Europe/Madrid"],
  ["西班牙", "卡斯蒂利亞-拉曼恰", "托萊多", "Europe/Madrid"],
  ["西班牙", "巴倫西亞", "瓦倫西亞", "Europe/Madrid"],
  ["西班牙", "穆爾西亞", "穆爾西亞", "Europe/Madrid"],
  ["西班牙", "安達盧西亞", "塞維亞", "Europe/Madrid"],
  ["西班牙", "埃斯特雷馬杜拉", "梅里達", "Europe/Madrid"],
  ["西班牙", "巴利阿里群島", "帕爾馬", "Europe/Madrid"],
  ["西班牙", "休達", "休達", "Africa/Ceuta"],
  ["西班牙", "梅利利亞", "梅利利亞", "Africa/Ceuta"],
  ["聖克里斯多福及尼維斯", "聖克里斯多福島", "巴士地", "America/St_Kitts"],
  ["聖克里斯多福及尼維斯", "尼維斯島", "查爾斯敦", "America/St_Kitts"],
  ["聖露西亞", "聖露西亞", "卡斯翠", "America/St_Lucia"],
  ["聖文森及格瑞那丁", "聖文森島", "金斯頓", "America/St_Vincent"],
  ["薩摩亞", "薩摩亞獨立國", "阿皮亞", "Pacific/Apia"],
  ["聖馬利諾", "聖馬利諾共和國", "聖馬力諾市", "Europe/San_Marino"],
  ["聖多美普林西比", "聖多美普林西比民主共和國", "聖多美", "Africa/Sao_Tome"],
  ["沙烏地阿拉伯", "沙烏地阿拉伯王國", "利雅德", "Asia/Riyadh"],
  ["塞內加爾", "塞內加爾共和國", "達卡", "Africa/Dakar"],
  ["賽爾維亞", "賽爾維亞共和國", "貝爾格勒", "Europe/Belgrade"],
  ["塞席爾", "馬埃島", "維多利亞港", "Indian/Mahe"],
  ["獅子山", "獅子山共和國", "自由城", "Africa/Freetown"],
  ["新加坡", "新加坡共和國", "新加坡", "Asia/Singapore"],
  ["斯洛伐克", "斯洛伐克共和國", "布拉提斯拉瓦", "Europe/Bratislava"],
  ["斯洛維尼亞", "斯洛維尼亞共和國", "盧比安納", "Europe/Ljubljana"],
  ["索羅門群島", "索羅門群島", "荷尼阿拉", "Pacific/Guadalcanal"],
  ["索馬利亞", "索馬利亞聯邦共和國", "摩加迪休", "Africa/Mogadishu"],
  ["南蘇丹", "南蘇丹共和國", "朱巴", "Africa/Juba"],
  ["斯里蘭卡", "斯里蘭卡民主社會主義共和國", "可倫坡", "Asia/Colombo"],
  ["蘇丹", "蘇丹共和國", "喀土穆", "Africa/Khartoum"],
  ["蘇利南", "蘇利南共和國", "帕拉馬里博", "America/Paramaribo"],
  ["史瓦帝尼", "史瓦帝尼王國", "姆巴巴內", "Africa/Mbabane"],
  ["瑞典", "瑞典王國", "斯德哥爾摩", "Europe/Stockholm"],
  ["瑞士", "瑞士聯邦", "蘇黎世", "Europe/Zurich"],
  ["敘利亞", "敘利亞阿拉伯共和國", "大馬士革", "Asia/Damascus"],
  ["塔吉克", "塔吉克共和國", "杜尚別", "Asia/Dushanbe"],
  ["坦尚尼亞", "坦尚尼亞聯合共和國", "三蘭港", "Africa/Dar_es_Salaam"],
  ["泰國", "泰王國", "曼谷", "Asia/Bangkok"],
  ["多哥", "多哥共和國", "洛美", "Africa/Lome"],
  ["東加", "東加王國", "東加塔布島", "Pacific/Tongatapu"],
  [
    "千里達及托巴哥",
    "千里達及托巴哥共和國",
    "西班牙港",
    "America/Port_of_Spain",
  ],
  ["突尼西亞", "突尼西亞共和國", "突尼斯市", "Africa/Tunis"],
  ["土耳其", "土耳其共和國", "伊斯坦堡", "Europe/Istanbul"],
  ["土庫曼", "土庫曼", "阿什哈巴德", "Asia/Ashgabat"],
  ["吐瓦魯", "吐瓦魯", "富納富提", "Pacific/Funafuti"],
  ["烏干達", "烏干達共和國", "坎帕拉", "Africa/Kampala"],
  ["烏克蘭", "烏克蘭", "基輔", "Europe/Kyiv"],
  ["阿拉伯", "阿拉伯聯合大公國", "杜拜", "Asia/Dubai"],
  ["烏拉圭", "烏拉圭東方共和國", "蒙特維多", "America/Montevideo"],
  ["烏茲別克", "烏茲別克共和國", "塔什干市", "Asia/Tashkent"],
  ["萬那杜", "萬那杜共和國", "維拉港", "Pacific/Efate"],
  ["梵蒂岡", "梵蒂岡城國", "梵蒂岡市", "Europe/Vatican"],
  ["委內瑞拉", "委內瑞拉玻利瓦共和國", "卡拉卡斯", "America/Caracas"],
  ["越南", "越南社會主義共和國", "胡志明市", "Asia/Ho_Chi_Minh"],
  ["葉門", "葉門共和國", "亞丁", "Asia/Aden"],
  ["尚比亞", "尚比亞共和國", "路沙卡", "Africa/Lusaka"],
  ["辛巴威", "辛巴威共和國", "哈拉雷", "Africa/Harare"],
] as [string, string, string, string][];
